### ISSUE TITLE
Feature Request: Add support allowing Brix readings for extraction yield calculations

### ISSUE THREAD

**Issue by wannabecoffeenerd** [graphefruit/Beanconqueror#226] opened 2021-06-01 05:13 UTC
Higher end VST and even Atago refractometers are out of reach for a lot of home baristas which makes getting extraction yield metrics inaccessible to many. Cheap optical brix meters have been shown to be adequate for home use and the standard rule of thumb is to use a factor of 0.85 to go from Brix to TDS. This really only works in the espresso range and also varies depending on the TDS.

There are better correlations available to convert Brix to TDS like this one that Atago seems to use
![TDS to Brix conversion](https://www.coffeelabequipment.com/TDS_AND_BRIX.jpg "TDS to Brix conversion")

It would be very useful and convenient to build this simple correlation into Beanconqueror and would help a lot of home baristas get more insight into their brews.

I am happy to help with this issue if someone more familiar with the app can give me some pointers.

**Comment by nhadler** [comment] 2021-06-01 18:40
I'd also really appreciate this feature being added. Visual brix meters are a fantastic low barrier entry point to measure EY for espresso and this would make the process far more streamlined. As well digital brix meter exist and offer a low price point.

**Comment by chaumein** [comment] 2021-06-01 18:57
This feature would be great!

**Comment by graphefruit** [comment] 2021-06-03 08:44
Extraction Yield is currently calculated like this: 
```
 public getExtractionYield(): string {
    const grindWeight: number = this.grind_weight;
    const brewQuantity: number = this.brew_beverage_quantity;
    const tds: number = this.tds;


    return this.toFixedIfNecessary(((brewQuantity * tds) / grindWeight),2).toString();

  }
  ```
  
  How would you see the Brix-Parameters buildt into Beanconqueror? (Choosement toggle if TDS or Brix, as a dropdown?)

If yes:
How shall I set in the formular when not aggregating with factor 0.85?

Thanks
Lars

**Comment by wannabecoffeenerd** [comment] 2021-06-03 18:26
I was thinking maybe have a separate Brix entry and compute tds based on that. That way, I can add a brix reading and the app would show me the TDS and EY.

```
 public getTdsFromBrix(): number {
    const brix: number = this.brix;

    return 0.0036*brix*brix + 0.7897*brix - 0.0071;
  }
```

**Comment by graphefruit** [comment] 2021-06-03 19:42
So to calculated TDS with Brix, there is no correlation with Brew quantity
/ beverage?

Am Do., 3. Juni 2021 um 20:27 Uhr schrieb wannabecoffeenerd <
***@***.***>:

**Comment by graphefruit** [comment] 2021-06-03 19:48
So to understand correctly.
You enter brix, brix will calculate TDS, and from this entry on TDS takes in place to get extraction yield right?

If this would be the use case I'm thinking about: Wouldn't it be easier to add an calculation popover where you can enter brix, and after this the value is "missed"?
Or is it needed to save the brix value later on?

**Comment by wannabecoffeenerd** [comment] 2021-06-03 21:04
Yeah, saving brix readings for later is probably not needed (except for debugging maybe?).

So the way you're suggesting is to press a brix button and enter the value there and that calculates and populates the TDS entry and forgets the entered brix value right? I think that should work fine.

**Comment by wannabecoffeenerd** [comment] 2021-06-03 21:06
I just realized that with the correlation in that image above, a 0 brix reading would give you a negative TDS! Should probably drop that last term from that equation.

**Comment by graphefruit** [comment] 2021-06-03 21:14
So the way you're suggesting is to press a brix button and enter the value there and that calculates and populates the TDS entry and forgets the entered brix value right? I think that should work fine.
-> Correct.

I just realised that with the correlation in that image above, a 0 brix reading would give you a negative TDS! Should probably drop that last term from that equation.
-> If the resulting value is less 0, I'd just preset it to 0 again.

**Comment by wannabecoffeenerd** [comment] 2021-06-03 21:44
Great! Thanks for taking this on Lars. Let me know if I can help in anyway in implementing this feature (since you added the help wanted label)

**Comment by graphefruit** [comment] 2021-06-04 17:51
@wannabecoffeenerd 
Could you please pass me a test version:
Grind weight: X
Beverage Quantity: Y
Brix: Z

-> Which TDS should be displayed, and which extraction yield?

---

I've just tested with:
Grams in: 18
Beverage quantity: 36 (1/2 ration - espresso)
Brix: 15
Calculateds TDS: 12.6555
Extraction Yield %: 25.31

Seems like a bit high?

**Comment by graphefruit** [comment] 2021-06-04 18:10
Workflow would be like: 
![image](https://user-images.githubusercontent.com/6260244/120845223-cd853400-c570-11eb-8804-cab3f0f0825d.png)
![image](https://user-images.githubusercontent.com/6260244/120845271-dd047d00-c570-11eb-9ba4-3e2fd4166cb2.png)

**Comment by wannabecoffeenerd** [comment] 2021-06-04 18:26
This looks awesome! I'll pull a shot later today and give you my test data to validate.

What equation are you using to convert from brix to tds btw?

**Comment by graphefruit** [comment] 2021-06-04 18:28
I used your formular
```
  const brix: number = this.brix;


    let tdsValue: number = (0.0036*brix + 0.7897)*brix;
    if (tdsValue < 0) {
      tdsValue = 0;
    }
 ```

**Comment by wannabecoffeenerd** [comment] 2021-06-05 01:39
Here is one of my measurements:
Grind weight: 17.1
Beverage Quantity: 54.2
Brix: 8.4

This should give
TDS: 6.887496
EY: 21.830543 %

Your example above also seems correct.

I am trying to see if someone with both a brix and TDS meter can get me some values for both so we can validate against that as well.

**Comment by graphefruit** [comment] 2021-06-05 11:55
Great!
Looking forward to hear from you.
The feature is developed now from my side on and will be available in the next Version 6.0

**Comment by wannabecoffeenerd** [comment] 2021-06-05 17:30
@graphefruit Here's a proper measurement of brix using an optical meter and tds using a refractometer:

Grind weight: 14
Beverage Quantity: 72
Brix: 6.1
TDS: 4.95

So, EY should be ~25.5% using both methods.

**Comment by graphefruit** [comment] 2021-06-05 17:35
Great! I'll look later again, thanks for research!

**Comment by wannabecoffeenerd** [comment] 2021-06-05 17:51
Thanks for adding this feature so quickly Lars! Do you have a sense of when 6.0 might be released?

**Comment by graphefruit** [comment] 2021-06-05 18:37
Actually July (mid-end) is planned, but I cant promise, many things to do left.

**Comment by graphefruit** [comment] 2021-06-05 18:51
Just checked, and works as intended.
Last question: Does the TDS value needs to be rounded (X.XX?) 
Else the calculated tds value actually is: 4.9511259999999995

**Comment by graphefruit** [comment] 2021-06-06 07:47
Okay I summed up to 2 decimals and fixed agaton formular aswell

**Comment by wannabecoffeenerd** [comment] 2021-06-06 09:37
Thanks, this all looks good!

Btw, really cool icon for the brix meter. Curious if you drew that yourself or found it somewhere.

**Comment by graphefruit** [comment] 2021-06-06 09:58
I'm using Icons8 or IonIcons (From the Ionicframework).

I gonna close this feature now, after its been finish in development.
Best regards
Lars

**Closed by graphefruit** 2021-06-06 09:58 UTC
Labels: enhancement
