### ISSUE TITLE
Option to select, that "Grind Setting" is a numerical value

### ISSUE THREAD

**Issue by LagaV** [graphefruit/Beanconqueror#495] opened 2023-02-22 14:50 UTC
I would appreciate a settings option to enable "Grind Setting" be defined as a numerical entry. Currently I always have to switch iOS keyboard first to enter my numerical value. Having directly a numerical keyboard at hand would help.

**Comment by graphefruit** [comment] 2023-02-22 19:35
Actually this is a duplicate of #461, never less: Not all grinders have a numerical value, so when enabling this option, this would be a feature-toggle which would be globally then.

**Comment by graphefruit** [comment] 2023-02-23 19:52
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/6260244/221014972-a82d0968-a8e9-4a06-8c08-b60058274017.png">
In the next version you can activate the feature toggle, so you'll just seeing a numeric input.

Please care: just numbers and "." will work, "," will be transferred to ".", nothing else allowed and will be replaced (like on the grind weight)

**Closed** 2023-02-25 19:44 UTC
Labels: duplicate, enhancement
